yaml_path = "./StreamingAvatarSDK.yaml"
sdk_path = "./sdk"
StreamingAvatarApi_remote_path = "https://api.github.com/repos/HeyGen-Official/StreamingAvatarSDK/contents/apis/StreamingAvatarApi.ts"
StreamingAvatarApi_local_path = "./sdk/apis/StreamingAvatarApi.ts"
runtime_remote_path = "https://api.github.com/repos/HeyGen-Official/StreamingAvatarSDK/contents/runtime.ts"
runtime_local_path = "./sdk/runtime.ts"
events_remote_path = "https://api.github.com/repos/HeyGen-Official/StreamingAvatarSDK/contents/events"
events_local_path = "./sdk/events"